package io.ruin.model.map.object.actions.impl.cities;

import io.ruin.model.map.object.actions.ObjectAction;
import io.ruin.model.map.object.actions.impl.Ladder;

public class Tirannwn {
    static {
        /*
        Iorwerth camp
         */
        ObjectAction.register(35846, 2200, 3262, 0, 1, (player, obj) -> {
            player.getMovement().teleport(2201, 9673, 0);
        });
        ObjectAction.register(35845, 2200, 9671, 0, 1, (player, obj) -> {
            player.getMovement().teleport(2201, 3261, 0);
        });
        /*
        Forest
         */
        //TODO: Autogenerated actions need animations and graphics
        ObjectAction.register(3938, 2302, 3223, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2303, 3222, 0);
            } else {
                player.getMovement().teleport(2303, 3225, 0);
            }
        });
        ObjectAction.register(3939, 2302, 3220, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2303, 3219, 0);
            } else {
                player.getMovement().teleport(2303, 3222, 0);
            }
        });
        ObjectAction.register(3938, 2302, 3217, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2303, 3216, 0);
            } else {
                player.getMovement().teleport(2303, 3219, 0);
            }
        });
        ObjectAction.register(3937, 2302, 3214, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2303, 3213, 0);
            } else {
                player.getMovement().teleport(2303, 3216, 0);
            }
        });
        ObjectAction.register(3939, 2278, 3229, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2279, 3228, 0);
            } else {
                player.getMovement().teleport(2279, 3231, 0);
            }
        });
        ObjectAction.register(3937, 2278, 3226, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2279, 3225, 0);
            } else {
                player.getMovement().teleport(2279, 3228, 0);
            }
        });
        ObjectAction.register(3938, 2278, 3223, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2279, 3222, 0);
            } else {
                player.getMovement().teleport(2279, 3225, 0);
            }
        });
        ObjectAction.register(3939, 2236, 3218, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2235, 3219, 0);
            } else {
                player.getMovement().teleport(2238, 3219, 0);
            }
        });
        ObjectAction.register(3937, 2233, 3218, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2232, 3219, 0);
            } else {
                player.getMovement().teleport(2235, 3219, 0);
            }
        });
        ObjectAction.register(3939, 2230, 3218, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2229, 3219, 0);
            } else {
                player.getMovement().teleport(2232, 3219, 0);
            }
        });
        ObjectAction.register(3938, 2227, 3218, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2226, 3219, 0);
            } else {
                player.getMovement().teleport(2229, 3219, 0);
            }
        });
        ObjectAction.register(3937, 2272, 3191, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2271, 3192, 0);
            } else {
                player.getMovement().teleport(2274, 3192, 0);
            }
        });
        ObjectAction.register(3939, 2269, 3191, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2268, 3192, 0);
            } else {
                player.getMovement().teleport(2271, 3192, 0);
            }
        });
        ObjectAction.register(3938, 2266, 3191, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2265, 3192, 0);
            } else {
                player.getMovement().teleport(2268, 3192, 0);
            }
        });
        ObjectAction.register(3939, 2238, 3148, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2237, 3149, 0);
            } else {
                player.getMovement().teleport(2240, 3149, 0);
            }
        });
        ObjectAction.register(3938, 2235, 3148, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2234, 3149, 0);
            } else {
                player.getMovement().teleport(2237, 3149, 0);
            }
        });
        ObjectAction.register(3937, 2232, 3148, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2231, 3149, 0);
            } else {
                player.getMovement().teleport(2234, 3149, 0);
            }
        });
        ObjectAction.register(3939, 2216, 3167, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2217, 3166, 0);
            } else {
                player.getMovement().teleport(2217, 3167, 0);
            }
        });
        ObjectAction.register(3938, 2216, 3164, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2217, 3163, 0);
            } else {
                player.getMovement().teleport(2217, 3166, 0);
            }
        });
        ObjectAction.register(3939, 2216, 3161, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2217, 3160, 0);
            } else {
                player.getMovement().teleport(2217, 3163, 0);
            }
        });
        ObjectAction.register(3998, 2187, 3169, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2188, 3168, 0);
            } else {
                player.getMovement().teleport(2188, 3170, 0);
            }
        });
        ObjectAction.register(3939, 2187, 3166, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2188, 3165, 0);
            } else {
                player.getMovement().teleport(2188, 3168, 0);
            }
        });
        ObjectAction.register(3999, 2187, 3163, 0, 1, (player, obj) -> {
            if (player.getPosition().getY() > obj.getPosition().getY()) {
                player.getMovement().teleport(2188, 3162, 0);
            } else {
                player.getMovement().teleport(2188, 3165, 0);
            }
        });
        ObjectAction.register(3937, 2237, 3248, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2236, 3249, 0);
            } else {
                player.getMovement().teleport(2239, 3249, 0);
            }
        });
        ObjectAction.register(3939, 2234, 3248, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(2233, 3249, 0);
            } else {
                player.getMovement().teleport(2236, 3249, 0);
            }
        });
        ObjectAction.register(8742, 2305, 3195, 0, 1, (player, obj) -> {
            if (player.getPosition().getX() > obj.getPosition().getX()) {
                player.getMovement().teleport(player.getPosition().getX()-2, 3195, 0);
            } else {
                player.getMovement().teleport(player.getPosition().getX()+2, 3195, 0);
            }
        });
    }
}
